os:
- linux
sudo: false
script:
- build.sh
deploy:
  provider: releases
  api_key:
    secure: iQl3bpKf2elpvAga5w/ybs5r3qoWK5Iet6fSvcCxWqbWykgso2r5kQFR0+qXSFNlCHzsjewFMrl6tu16obx/Yi6rQ5a8n3lY5WbzMo5qnEzojO5p4js+BeYu0FTKof6inz0DMzUR9ZrTlNcSRYW2tP36smF0kUtjFLnJwQ5QBFzuB36Y6n2XGP1ftbdzZ8Blb76EOdT8fA6BniVLI8/lTUQXjvAtl1n1dBm04EST+hQo3WVouIj6gTvdhppWlOMBvw6VKNhZZccSi2asWnx0qL8ShrTxEdSIZQpgkkMEMVJPxUL+NGZTuxvfNLskqDeajEzxFfsIy8Bl5KkPNRa510nVWoCeEQkunQqrznk3cmn4Oeg1VZDEVyhILuaOaDnWZg9A11JIsPWyzR323fPj06i+i/g1TUNZAhozUqRaB9Uj5MflSlqk29VrFYMW5orCjcoD1DVpDbtxFOTQN8KNgWawcQUTH+AKXNzYo1d5CjX1NPFkwdUbTlenj4CnNgunnsBcfldHZyEn+zJQZxfSI0h1FIq9rmPKz2EDtHq9gBJfEVfAhAdShFs9aCpn16USoLvt+FVat7UT6ktxVALPAYxOjUuK/gphV50AaSB7zBOPA1d5ikewU07kFM1GcitsK45e9LxGVkp+TuMdj+dR/WHdsW60wUFyNE74ZW2fbVQ=
  file: helloWorld.sh
  skip_cleanup: true
  prerelease: true
  on:
    tags: true
